import Footer from "@/components/blocks/footer";
import type { Metadata } from "next";
import { ViewTransitions } from "next-view-transitions";
import localFont from "next/font/local";
import "../globals.css";

import { ReactLenis } from 'lenis/react';


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {




    return (
        <section className="relative z-10 w-full py-12 md:py-48 min-h-screen flex flex-col justify-center bg-muted-foreground overflow-hidden">
            {children}
        </section>
    );
}
