import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { FloatingNavBar } from "@/components/blocks/floating-navbar";
import { Contact, HomeIcon, InfoIcon } from "lucide-react";
import Footer from "@/components/blocks/footer";
import { ViewTransitions } from "next-view-transitions";

import { ReactLenis, useLenis } from 'lenis/react'
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const navItems = [
    { name: "Início", link: "/", icon: <HomeIcon /> },
    { name: "Sobre", link: "/about", icon: <InfoIcon /> },
    { name: "Contato", link: "/contact", icon: <Contact /> },
  ]



  return (
    <ViewTransitions>
      <html lang="en">
        <ReactLenis root options={{ touchMultiplier: 0, syncTouch: false }}>

          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
          >
            <FloatingNavBar navItems={navItems} />
            {children}
            <Footer />
          </body>
        </ReactLenis>
      </html>
    </ViewTransitions>
  );
}
