version: "3.8"

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d  # Aqui o dump sql será importado
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SCHEMA: public  # Se necessário
      DATABASE_SSL: 'false'
    ports:
      - "1337:1337"

  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - "3000:3000"

volumes:
  pgdata: